name: mo_swd392
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0" # You can adjust the version if needed.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.4
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.0.20
  font_awesome_flutter: ^10.2.0
  image_picker: ^0.8.5+3
  table_calendar: ^3.0.0
  fluttertoast: ^8.2.8
  http: ^1.2.2 # Add this if you need the http package.
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  provider: ^6.1.2
  intl: ^0.17.0
  firebase_auth: ^5.3.2
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Phiên bản đã cập nhật của flutter_lints.

flutter:
  uses-material-design: true
  assets:
    - assets/images/google.png
    - lib/resource/
