// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6NlsSlo9F2uS1ts6Cc5gYI8pdBl_tOEA',
    appId: '1:853981095655:android:b6bfa8eb5a613fc741e442',
    messagingSenderId: '853981095655',
    projectId: 'mentor-booking-3d46a',
    storageBucket: 'mentor-booking-3d46a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXjGFVhl23TiMMG1dg7-xIr3B4uGbpX5c',
    appId: '1:853981095655:ios:a12eb141dca9be4d41e442',
    messagingSenderId: '853981095655',
    projectId: 'mentor-booking-3d46a',
    storageBucket: 'mentor-booking-3d46a.appspot.com',
    iosClientId:
        '853981095655-01492c1atp0m6c06uouovbid1gsldudj.apps.googleusercontent.com',
    iosBundleId: 'com.example.moSwd392',
  );
}
